apiVersion: v1
kind: Template

metadata:
  name: demo4-web-game-ui

parameters:
  - name: APPLICATION_NAME
    value: demo4-web-game-ui
    required: true
  - name: REPLICAS
    value: "1"
    required: true
  - name: IMAGE_REPOSITORY
    displayName: Image Repository
    value: quay.io/redhatdemo/demo4-web-game-nginx:latest
    required: true
  - name: KEY
  - name: CERTIFICATE
  - name: CA_CERTIFICATE

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: ${REPLICAS}
      revisionHistoryLimit: 2
      selector:
        app: ${APPLICATION_NAME}
      strategy:
        rollingParams:
          timeoutSeconds: 3600
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          containers:
            - image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
      triggers:
        - type: ConfigChange


  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      ports:
        - name: http
          port: 8080
      selector:
        app: ${APPLICATION_NAME}

  # backwards compatibility (for training app)
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: demo4-web-game
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}
      tls:
        termination: edge
        key: |-
          ${KEY}
        certificate: |-
          ${CERTIFICATE}
        caCertificate: |-
          ${CA_CERTIFICATE}
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None


  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: play
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}
      tls:
        termination: edge
        key: |-
          ${KEY}
        certificate: |-
          ${CERTIFICATE}
        caCertificate: |-
          ${CA_CERTIFICATE}
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None

